# Generated by Django 5.1.5 on 2025-01-15 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_threads', to=settings.AUTH_USER_MODEL)),
                ('beta_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('alpha_user', 'beta_user')},
            },
        ),
        migrations.CreateModel(
            name='ChatText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatting.chatthread')),
            ],
        ),
    ]
