# Generated by Django 5.1.5 on 2025-01-17 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatthread',
            old_name='alpha_user',
            new_name='origin_user',
        ),
        migrations.RenameField(
            model_name='chatthread',
            old_name='beta_user',
            new_name='other_user',
        ),
        migrations.AlterUniqueTogether(
            name='chatthread',
            unique_together={('origin_user', 'other_user')},
        ),
        migrations.AddField(
            model_name='chatthread',
            name='room_name',
            field=models.CharField(default=6, max_length=500),
            preserve_default=False,
        ),
    ]
