# Generated by Django 5.1.5 on 2025-01-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0003_alter_chatthread_origin_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
